spring:
#  profiles:
#    active: local
  application:
    name: tc2-monolitico
  data:
    mongodb:
      uri: mongodb+srv://${MONGO_USER}:${MONGO_PWD}@${MONGO_HOST}/${MONGO_DB}?authSource=admin
  rabbitmq:
    host: ${RABBITMQ_HOST}
    username: ${RABBITMQ_USER}
    virtual_host: ${RABBITMQ_VH}
    password: ${RABBITMQ_PWD}

management:
  endpoints:
    web:
      exposure:
        include: "*"