spring:
  application:
    name: tc2-monolitico
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@monolitico.axf2whd.mongodb.net/monolitico?authSource=admin
  rabbitmq:
    host: gorilla-01.lmq.cloudamqp.com
    username: fwvxmear
    virtual_host: fwvxmear
    password: Gq1ORWwgNe2ZaBtLPptdLtT38SRNG_xl

management:
  endpoints:
    web:
      exposure:
        include: "*"